default_stages: [commit]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: forbid-new-submodules
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: no-commit-to-branch
      args: [-b, develop]
- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
    - id: black
      language_version: python3.11
      additional_dependencies:
        - 'click==8.0.0'
- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
    - id: flake8
      args: [--config=.flake8]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.5.1
  hooks:
    - id: mypy
      args: [--config-file, pyproject.toml]

- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
    - id: shellcheck
- repo: https://github.com/asottile/pyupgrade
  rev: v3.13.0
  hooks:
    - id: pyupgrade
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
- repo: https://github.com/econchick/interrogate
  rev: 1.4.0
  hooks:
    - id: interrogate
      args: [-i, --fail-under=80]
